### ISSUE TITLE
Pdpyras 5.0 misses deprecation install-requirement

### ISSUE THREAD

**Issue by potiuk** [PagerDuty/pdpyras#100]
The Pdpyras 5.0.0 released an hour ago misses `deprecation` module in install_requires.

The deprecation module is imported here: 

https://github.com/PagerDuty/pdpyras/blob/main/pdpyras.py#L17

This has been detected by Airflow's `canary` builds (pdpyras is used by pagerduty provider of Airflow).

**Comment by potiuk** [comment]
Whoa. That was quick! Thanks!

**Comment by Deconstrained** [comment]
Thank you @potiuk  for bringing this so promptly to our attention! v5.0.1 has just been released. Sorry for the inconvenience!

**Comment by potiuk** [comment]
Fantastic! Yep. We noticed yanking - this way we won't have to even exclude 5.0.0 :)
