### ISSUE TITLE
Wrapped entity key error for Tags linked entity endpoint

### ISSUE THREAD

**Issue by DianaOlympos** [PagerDuty/pdpyras#130]
The `tags/{id}/{entity_type}` endpoint is officially supported by pdpyras (see https://github.com/PagerDuty/pdpyras/blob/main/pdpyras.py#L198), but it is a paginated wrapped entity endpoint that does not respect the rules, as it uses the entity_type as its wrapper key. We get errors if we try to use iter_all/list_all on it.

Is there a solution, or should I just use the "raw" queries and do my loop pagination myself?

I would be happy to make a PR if an idea of what the solution should be is offered; right now, I am not sure of the best way, if any.

**Comment by Deconstrained** [comment]
For which values of `{entity_type}` do the errors happen, and what are the errors?

The documentation for [GET /tags/{id}/{entity_type}](https://developer.pagerduty.com/api-reference/5a579467410f7-get-connected-entities) indicates that the entity wrapper name matches the last path node. If the API is not always responding with the documented schema, it is within reason to consider this a bug in the API itself. In that case, I'd be glad to create an issue report for it.

**Comment by Deconstrained** [comment]
I think I identified the issue (`pdpyras.URLError`?). Thanks for bringing it to my attention. I can think of a few ways to make the client recognize the endpoint as an exception to the otherwise-global rule (which I overlooked last spring when I worked on v5.0.0) and the best way is an allowlist of canonical paths.

**Comment by DianaOlympos** [comment]
Thank you so much! yeah, when I started diving, it definitely sounded like this was a "strange" endpoint from the data type pov.

If it helps, it was with users :)

**Comment by Deconstrained** [comment]
For the record: the solution decided upon was to expand the single canonical path into multiple paths as though they were separately documented for each explicit `{entity_type}`. For each of the resulting paths (which end in a constant string `users`, `teams` or `escalation_policies` vs. a variable parameter) the entity wrapping logic works as it should for any other path with no need for special new logic particular to this endpoint.

If new entity types are added to the tags API endpoint in question, support for them will need to be added by updating the script that generates the global `CANONICAL_PATHS` list (and updating the declaration of said global accordingly).
