### ISSUE TITLE
Publishing wheels on PyPI

### ISSUE THREAD

**Issue by finlaysawyer** [PagerDuty/pdpyras#133]
Hey :wave:

I noticed that you aren't currently publishing any wheel binaries on PyPI. If you'd be able to do this, it would really help from a platform compatibility perspective as we generally run pip install with a specific `--platform` and `--only-binary=:all:`, meaning we can only download wheels.

There's also a bunch of other advantages like a faster install and a generally more consistent / reliable experience.

Thanks!

**Comment by Deconstrained** [comment]
To make this more portable (to other maintainers) I will take some time to investigate possible solutions involving CircleCI. I will probably be revisiting alternate documentation hosting to GitHub pages and a CircleCI-powered documentation build, which will overlap a lot.
