### ISSUE TITLE
Question - How to get all Pagerduty incident notes via Pdpyras library

### ISSUE THREAD

**Issue by gtang31-te** [PagerDuty/pdpyras#144]
I know how to make a GET request to the [incident notes API endpoint](https://developer.pagerduty.com/api-reference/a1ac30885eb7a-list-notes-for-an-incident) but how do I leverage the `pdpyras` library to do so? I can get all `incidents`

```
from pdpyras import APISession
api_token = 'MY_TOKEN'
session = APISession(api_token)

for incident in session.iter_all('incidents'):
    print(incident)
```
but i cannot see any information related to notes, so i am suspecting i should not be passing `'incidents'` to my `sessions.iter_all` method. I have been looking through the library's [source code](https://github.com/PagerDuty/pdpyras/blob/main/pdpyras.py#L146) but I have not gotten anywhere with that. Any help would be appreciated.

**Comment by Deconstrained** [comment]
Greetings! Incident notes are recorded as log entries.

You can thus retrieve them by querying [log entries for an incident](https://developer.pagerduty.com/api-reference/367602cbc1c28-list-log-entries-for-an-incident) (or querying [all log entries](https://developer.pagerduty.com/api-reference/c661e065403b5-list-log-entries) to get them for all incidents) and then filtering for `AnnotateLogEntry` type entries.

This for example gets an iterable filter object that returns notes (and you can also filter by team IDs and enable other options by sending optional parameters via the `parameters` keyword argument to `iter_all`, `list_all` etc.):

```python
notes = filter(
    lambda ile: ile['type'] == 'annotate_log_entry',
    session.iter_all('/log_entries')
)
```

**Comment by Deconstrained** [comment]
Added to the new library's documentation
