### ISSUE TITLE
HTTP 400 when hitting "log_entries" endpoint

### ISSUE THREAD

**Issue by gtangthousandeyes** [PagerDuty/pdpyras#37]
I just noticed this error when trying to use your library to retrieve my organization's log entries

```
>>> data_list = session.list_all('log_entries')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gtang/.pyenv/versions/etl_env/lib/python3.6/site-packages/pdpyras.py", line 1074, in list_all
    return list(self.iter_all(path, **kw))
  File "/Users/gtang/.pyenv/versions/etl_env/lib/python3.6/site-packages/pdpyras.py", line 999, in iter_all
    r.status_code, path), response=r)
pdpyras.PDClientError: Encountered HTTP error status (400) response while iterating through index endpoint log_entries.
```

Not sure if the error is coming from PagerDuty's API or your wrapper but I figure I post this issue here

**Comment by Deconstrained** [comment]
Resolved in version 4.1.2; iteration in big indexes like `incidents` and `log_entries` will not fail once it reaches the maximum but will return whatever it gets and print a warning message with an explanation to the log.
