### ISSUE TITLE
Uncaught Exception on 500 Error

### ISSUE THREAD

**Issue by shonin** [PagerDuty/pdpyras#40]
Line 1157 raises an uncaught key error when a 500 is returned, as the request_id is not in the header. https://github.com/PagerDuty/pdpyras/blob/master/pdpyras.py#L1157

The `request_id` is already available, so this can simply read: 

```python
if int(status) == 500:
            self.log.error("PagerDuty API server error (%d)! "
                "For additional diagnostics, contact PagerDuty support "
                "and reference x_request_id=%s / date=%s",
                status, request_id, request_date)
```

I have a branch ready to go, but i don't have push access to this repo.

**Comment by Deconstrained** [comment]
Hi @shonin,

Thanks for pointing this out! Easy fix.

Which API endpoint was being requested when this error came up? Our API should respond with this header.

**Comment by shonin** [comment]
It was the response plays end point, which I see intermittent problems with.
