### ISSUE TITLE
dedup_key Not passed to incident 

### ISSUE THREAD

**Issue by genebean** [PagerDuty/pdpyras#44]
When I trigger an event like below the dedup key does not appear anywhere on the resulting incident. Is this a bug or am I doing something wrong? My understanding is it would show up there and be usable for querying for the incident post creation.  

```python
session = EventsAPISession(token)
# all parameters are variables omitted here 
response = session.trigger(
        summary, source, dedup_key, severity,
        payload, custom_details, images, links)
```

**Comment by hunner** [comment]
The dedup key is the `incident_key` field if you click "View message" on the incident in PD's timeline. The `response` back if you `print` it should be the dedup key as well, and acknowledgements or resolutions with that key should update the appropriate incident.

What seems strange to me is that the `source` doesn't seem to be showing up in the PD UI, which I would expect to have show up even more than the dedup key.

**Comment by hunner** [comment]
Ah, if you visit an incident and click on a specific alert, the alert details show the source and the "Alert Key" as it's called:
![Screen Shot 2020-10-23 at 10 23 00](https://user-images.githubusercontent.com/91972/97034515-e842f500-1519-11eb-8b09-d18a1edbd6f9.png)

**Comment by genebean** [comment]
For the incidents I’ve created the dedupe_key does not show up in the incident key... it actually always shows was none.

**Comment by jchiare** [comment]
@genebean are you looking at an incident which has alerts associated with it? 

Because then the dedup key will be present in the alert and not incident.

Per the doc: https://support.pagerduty.com/docs/alerts#enabling-alerts
> When enabled, the incident_key is deprecated and becomes null. De-duplication will be based on on the alert_key instead of the incident_key.
