### ISSUE TITLE
How to set proxy for pdpyrsa

### ISSUE THREAD

**Issue by zelong430** [PagerDuty/pdpyras#47]
Our enterprise network require to use a proxy to access  https://api.pagerduty.com. I can't find a way to set the proxy for EventAPISession. Can someone here provide some helps our point me to the correct instructions/docs?

**Comment by badnetmask** [comment]
pdpyrsa uses the Python requests library. I am unable to test right now, but I would suggest that you try environment variables, [like explained in the documentation](https://requests.readthedocs.io/en/master/user/advanced/#proxies). In theory, it should work just fine.

**Comment by zelong430** [comment]
Hi Thanks for the reply,

I was able to get it work by something like:

   session = pdpyras.EventsAPISession(CONFIG['our-pager-duty-key'])
   session.proxies.update(PD_PROXY)
