### ISSUE TITLE
Support for TAGS api

### ISSUE THREAD

**Issue by aalbertson** [PagerDuty/pdpyras#50]
Hi There,

First off, this is a great project and I'm really enjoying using it. I've written a few things so far and they work well.

However, I'm in a spot where I'm trying to assemble a full user list of specific elements (e.g. query all users and their emails, roles, teams, tags) and well, the TAGS api is completely separate and while of course I can write against just a regular client, it would be great if that was another component of pdpyras so I can easily pull it all together.

Thanks!

**Comment by Deconstrained** [comment]
Hi @aalbertson ,

Tagging's API is not yet publicly-documented, and while it may be possible to reverse engineer it, we generally advise against using undocumented APIs in any production-stage process as they may be subject to change.

The API might not (I suspect) follow the same norms as APIs for our core data models (Services for instance), and so to utilize it, one will most likely need to use the regular `post`/`get`/`put`/`delete` methods as opposed to `r*`.
