### ISSUE TITLE
PDClientError: PUT /incidents: API responded with non-success status (400)

### ISSUE THREAD

**Issue by vibhutigoel** [PagerDuty/pdpyras#51]
We are using below function to resolve the incident 

    def resolve_incident(self, incident_ids):
        for incident_id in incident_ids:
            incident = self.session.rget("incidents/" + incident_id)
            try:
                if incident['status'] != 'resolved':
                    self.session.rput(
                        "incidents",
                        json=[{'id': incident_id, 'type': 'incident_reference', 'status': 'resolved'}]
                    )
                else:
                    print "Incident: " + incident_id + " is already resolved!"
            except PDClientError:
                print "Could not resolve incident: " + incident_id
                traceback.print_exc()
                raise RuntimeError("Could not resolve incident: " + incident_id)
        return True

suddenly its started throwing below error  : 
**PDClientError: PUT /incidents: API responded with non-success status (400)**
--
 As per my finding there is some issue with **rput** 
Is anything changes in the pagerduty API ? or in pdpyras ?

**Comment by yawboateng** [comment]
getting the same with rpost

**Comment by yawboateng** [comment]
ah works for me now, PD requires an extra header called from for some calls, you can set it when instantiating the class. `PagerDutyAPISession("apikey", default_from='test@useremail.com')` This is already noted in the README.

**Comment by Deconstrained** [comment]
FYI, if more detail about a response is needed (i.e. validation errors), to make it easier to troubleshoot when using any of the methods that raise exceptions for non-2xx response statuses, the `response` property if non-`None` should be a `requests.Response` object. The `text` property / `json()` method of such an object contains the body, which should contain errors reported by the API, if any.
