### ISSUE TITLE
Mismatch in supported Python versions between README and PyPI package. 

### ISSUE THREAD

**Issue by 0xadaw** [PagerDuty/pdpyras#80]
PyPI pdpyras package requires Python versions >=3.5: 
https://pypi.org/project/pdpyras/

Yet README suggests support is up to v3.8: 
> Tested in / support for Python 2.7 through 3.8
(source: [https://github.com/PagerDuty/pdpyras/tree/v4.4.0#features](url))

This needs clarification, please.

**Comment by Deconstrained** [comment]
Oof, thanks for catching this.

Support for Python 2 was dropped in v4.3.0
