### ISSUE TITLE
Release 4.5.1 `ModuleNotFoundError: No module named 'requests'`

### ISSUE THREAD

**Issue by scottx611x** [PagerDuty/pdpyras#91]
👋 Hey there @Deconstrained 😄. I'm observing a behavior where the changes from here: https://github.com/PagerDuty/pdpyras/commit/bab036820725ce27539bb5eb3fbe45ddcea4a5db#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R3 seem to be manifesting as the following issue upon installation of release `4.5.1`.

I assume that anyone else that doesn't explicitly specify `requests` as a requirement of their own would see the same since this occurs before `pdpyras` can install its own `requests` requirement.

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h5zdz16c/pdpyras/setup.py", line 3, in <module>
        from pdpyras import __version__
      File "/tmp/pip-install-h5zdz16c/pdpyras/pdpyras.py", line 13, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
```

It looks like this was able to sneak by CI checks due to the one-off `requirements.txt` install happening here: https://github.com/PagerDuty/pdpyras/blob/66740e3b344522d8b30b6e2fb7c84bcfa54b38b9/.circleci/config.yml#L23

**Comment by Deconstrained** [comment]
Hi @scottx611x ,

Thank you for catching this. I had forgotten that is the very reason why I had originally declared the version in more than one place 🤦

**Comment by scottx611x** [comment]
No prob! Easy fix on our end, just wanted to inform you 👍
