### ISSUE TITLE
Didn't find a way to `pass statuses[] more than once` 

### ISSUE THREAD

**Issue by thanch2n** [PagerDuty/pdpyras#98]
Looks we can't use same key with different values in dict and pass to params.
But on server side it supports `To query multiple statuses, pass statuses[] more than once`, 
https://developer.pagerduty.com/api-reference/9d0b4b12e36f9-list-incidents.

```python
        params = {
            'statuses[]': 'acknowledged',
            'statuses[]': 'triggered',
            'statuses[]': 'resolved',
        }
        for incident in session.iter_all('incidents', params):
            yield incident
```

**Comment by Deconstrained** [comment]
Note, `pdpyras.APISession` is a wrapper of [requests.Session](https://requests.readthedocs.io/en/latest/api/#request-sessions). 

Per https://requests.readthedocs.io/en/latest/user/quickstart/#passing-parameters-in-urls), The way to do this is passing multi-valued parameters as lists `'statuses[]': ['acknowledged', 'triggered', 'resolved']`

**Comment by Deconstrained** [comment]
Added to list of things to document with the release of v5.0

**Comment by Deconstrained** [comment]
#97 will take care of this
